server:
  port: 1323

logging:
  level:
    ROOT: Debug
    org.hibernate.SQL: DEBUG
    com.patelbnb: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: patelbnb-backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: patelbnb


  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: patelbnb
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

okta:
  oauth2:
    issuer: https://patelbnb.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_XaTHFpWudEP7lDnI

