logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    com.patelbnb: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESS_URL}:${POSTGRESS_PORT}/${POSTGRESS_DBNAME}
    username: ${POSTGRESS_USERNAME}
    password: ${POSTGRESS_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: patelbnb
  liquibase:
    contexts: prod
    default-schema: patelbnb

server:
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

application:
  cors:
    allowed-origins: "https://patelbnb.work.gd"
  auth0:
    role-landlord-id:${AUTH0_ROLE_LANDLORD_ID}
